image:
  repository: dokploy/dokploy
  pullPolicy: IfNotPresent
  tag: latest

resources:
  limits:
    cpu: 1000m
    memory: 1Gi

dokployConfig:
  password: ''
  nodeName: dokploy_node
  npmRegistry: "https://registry.npmmirror.com"
  pnpmRegistry: "https://registry.npmmirror.com"
  redis_host: "dokploy-redis"
  redis_port: 6379
  redis_password: "2469"
  additionalEnvs: []

dokployRunAs:
  user: 1000
  group: 1000

dokployNetwork:
  httpPort: 9000
  targetPort: 3000
  hostNetwork: false
  certificateID:

dokployStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []