image:
  repository: dokploy/dokploy
  tag: latest
  pullPolicy: IfNotPresent

dokployConfig:
  password: ""
  nodeName: "dokploy_node"
  npmRegistry: "https://registry.npmmirror.com"
  pnpmRegistry: "https://registry.npmmirror.com"
  additionalEnvs:
    - name: REDIS_HOST
      value: "dokploy-redis"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      value: "2469"

dokployNetwork:
  httpPort: 9000
  targetPort: 3000
  hostNetwork: false
  certificateID: null

dokployStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []

dokployRunAs:
  user: 1000
  group: 1000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  data:
    enabled: true
    mountPath: /app/data
    size: 1Gi

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

service:
  type: ClusterIP
  port: 9000
  targetPort: 3000

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "2469"

ingress:
  enabled: false